//package popcorn;

//Import Servlet Libraries
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.WebServlet; // @WebServlet

//Import Java Libraries
import java.io.*;
import java.util.*;
import java.lang.*;

import com.google.gson.Gson;

// Used in https://codesandbox.io/s/swe-432-react-popcorn-sales-k3b9i?file=/src/popcorn.js
// Part of the popcorn Ajax example.
// The response software component.
// Called from the JS with a zipcode, returns a city and state
@WebServlet(name = "zipLookup", urlPatterns = {"/zipLookup"})
public class zipLookup extends HttpServlet
{
  private Map<String, String> zipCityState;

   public void processRequest(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException
   {
      // enable external requests
      response.setHeader("Access-Control-Allow-Origin", "*");
      response.setHeader("Access-Control-Allow-Methods", "*");
      response.setHeader("Access-Control-Allow-Headers", "*");
      
      response.setContentType("aplication/json");
     
      PrintWriter out = response.getWriter();

      String zip = request.getParameter("zip");
      String cityst = zipCityState.get(zip);
     
      String state = null;
      String city = null;
      
      Map<String, String> data = new HashMap<String, String>();
      
      if (cityst != null) {
         String[] stateAndCity = cityst.split(", ");
         state = stateAndCity[0];
         city = stateAndCity[1];
      }
      
      data.put("state", state);
      data.put("city", city);
      out.print(new Gson().toJson(data));
      out.close();
   }

    // Method doPost - just calls processRequest
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
       processRequest(request, response);
    }

    // Method doGet - just calls processRequest
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
       processRequest(request, response);
    }


   public void init()
   {
      // Create and initialize the Mapping
      zipCityState = new HashMap<String, String>();
      // From http://www.census.gov/tiger/tms/gazetteer/zips.txt
      // Ouch ... Java error: "code too large"
      // A single method in a Java class may be at most 64KB of bytecode.
      // Over 29,000 entries.
      // Broke them up into groups of 4000, each one in a separate method.
      // Ouchy again ... Java error: "too many constants"
      // Okay, let's just keep KY and VA

      zipCityState.put("40003", "KY, BAGDAD");
      zipCityState.put("40004", "KY, BARDSTOWN");
      zipCityState.put("40006", "KY, BEDFORD");
      zipCityState.put("40007", "KY, BETHLEHEM");
      zipCityState.put("40008", "KY, BLOOMFIELD");
      zipCityState.put("40009", "KY, BRADFORDSVILLE");
      zipCityState.put("40010", "KY, BUCKNER");
      zipCityState.put("40011", "KY, CAMPBELLSBURG");
      zipCityState.put("40012", "KY, CHAPLIN");
      zipCityState.put("40013", "KY, DEATSVILLE");
      zipCityState.put("40014", "KY, CRESTWOOD");
      zipCityState.put("40019", "KY, EMINENCE");
      zipCityState.put("40022", "KY, FINCHVILLE");
      zipCityState.put("40023", "KY, FISHERVILLE");
      zipCityState.put("40026", "KY, GOSHEN");
      zipCityState.put("40028", "KY, HOWARDSTOWN");
      zipCityState.put("40031", "KY, LA GRANGE");
      zipCityState.put("40033", "KY, LEBANON");
      zipCityState.put("40036", "KY, LOCKPORT");
      zipCityState.put("40037", "KY, LORETTO");
      zipCityState.put("40040", "KY, MACKVILLE");
      zipCityState.put("40045", "KY, MILTON");
      zipCityState.put("40046", "KY, MOUNT EDEN");
      zipCityState.put("40047", "KY, MOUNT WASHINGTON");
      zipCityState.put("40050", "KY, NEW CASTLE");
      zipCityState.put("40051", "KY, TRAPPIST");
      zipCityState.put("40055", "KY, PENDLETON");
      zipCityState.put("40056", "KY, PEWEE VALLEY");
      zipCityState.put("40057", "KY, CROPPER");
      zipCityState.put("40059", "KY, PROSPECT");
      zipCityState.put("40060", "KY, RAYWICK");
      zipCityState.put("40061", "KY, SAINT CATHARINE");
      zipCityState.put("40062", "KY, SAINT FRANCIS");
      zipCityState.put("40065", "KY, SHELBYVILLE");
      zipCityState.put("40067", "KY, SIMPSONVILLE");
      zipCityState.put("40068", "KY, SMITHFIELD");
      zipCityState.put("40069", "KY, MAUD");
      zipCityState.put("40070", "KY, SULPHUR");
      zipCityState.put("40071", "KY, TAYLORSVILLE");
      zipCityState.put("40075", "KY, TURNERS STATION");
      zipCityState.put("40076", "KY, WADDY");
      zipCityState.put("40077", "KY, WESTPORT");
      zipCityState.put("40078", "KY, WILLISBURG");
      zipCityState.put("40103", "KY, 40103");
      zipCityState.put("40104", "KY, BATTLETOWN");
      zipCityState.put("40106", "KY, BIG SPRING");
      zipCityState.put("40107", "KY, BOSTON");
      zipCityState.put("40108", "KY, BRANDENBURG");
      zipCityState.put("40109", "KY, BROOKS");
      zipCityState.put("40111", "KY, CLOVERPORT");
      zipCityState.put("40114", "KY, CONSTANTINE");
      zipCityState.put("40115", "KY, CUSTER");
      zipCityState.put("40117", "KY, EKRON");
      zipCityState.put("40118", "KY, FAIRDALE");
      zipCityState.put("40119", "KY, GLEN DEAN");
      zipCityState.put("40121", "KY, FORT KNOX");
      zipCityState.put("40140", "KY, GARFIELD");
      zipCityState.put("40141", "KY, 40141");
      zipCityState.put("40142", "KY, GUSTON");
      zipCityState.put("40143", "KY, MOOLEYVILLE");
      zipCityState.put("40144", "KY, LOCUST HILL");
      zipCityState.put("40145", "KY, HUDSON");
      zipCityState.put("40146", "KY, IRVINGTON");
      zipCityState.put("40150", "KY, LEBANON JUNCTION");
      zipCityState.put("40152", "KY, MC DANIELS");
      zipCityState.put("40157", "KY, PAYNEVILLE");
      zipCityState.put("40160", "KY, RADCLIFF");
      zipCityState.put("40161", "KY, RHODELIA");
      zipCityState.put("40162", "KY, RINEYVILLE");
      zipCityState.put("40163", "KY, 40163");
      zipCityState.put("40164", "KY, SE REE");
      zipCityState.put("40165", "KY, SHEPHERDSVILLE");
      zipCityState.put("40170", "KY, STEPHENSPORT");
      zipCityState.put("40171", "KY, UNION STAR");
      zipCityState.put("40175", "KY, VINE GROVE");
      zipCityState.put("40176", "KY, WEBSTER");
      zipCityState.put("40177", "KY, WEST POINT");
      zipCityState.put("40178", "KY, WESTVIEW");
      zipCityState.put("40202", "KY, LOUISVILLE");
      zipCityState.put("40203", "KY, LOUISVILLE");
      zipCityState.put("40204", "KY, LOUISVILLE");
      zipCityState.put("40205", "KY, LOUISVILLE");
      zipCityState.put("40206", "KY, SAINT MATTHEWS");
      zipCityState.put("40207", "KY, SAINT MATTHEWS");
      zipCityState.put("40208", "KY, LOUISVILLE");
      zipCityState.put("40209", "KY, LOUISVILLE");
      zipCityState.put("40210", "KY, LOUISVILLE");
      zipCityState.put("40211", "KY, LOUISVILLE");
      zipCityState.put("40212", "KY, LOUISVILLE");
      zipCityState.put("40213", "KY, LOUISVILLE");
      zipCityState.put("40214", "KY, LOUISVILLE");
      zipCityState.put("40215", "KY, LOUISVILLE");
      zipCityState.put("40216", "KY, SHIVELY");
      zipCityState.put("40217", "KY, LOUISVILLE");
      zipCityState.put("40218", "KY, BUECHEL");
      zipCityState.put("40219", "KY, OKOLONA");
      zipCityState.put("40220", "KY, LOUISVILLE");
      zipCityState.put("40222", "KY, LYNDON");
      zipCityState.put("40223", "KY, ANCHORAGE");
      zipCityState.put("40228", "KY, BUECHEL");
      zipCityState.put("40229", "KY, OKOLONA");
      zipCityState.put("40241", "KY, LYNDON");
      zipCityState.put("40242", "KY, LYNDON");
      zipCityState.put("40243", "KY, MIDDLETOWN");
      zipCityState.put("40245", "KY, LOUISVILLE");
      zipCityState.put("40258", "KY, PLEASURE RIDGE P");
      zipCityState.put("40272", "KY, VALLEY STATION");
      zipCityState.put("40291", "KY, FERN CREEK");
      zipCityState.put("40299", "KY, JEFFERSONTOWN");
      zipCityState.put("40311", "KY, CARLISLE");
      zipCityState.put("40312", "KY, WESTBEND");
      zipCityState.put("40313", "KY, CLEARFIELD");
      zipCityState.put("40316", "KY, DENNISTON");
      zipCityState.put("40322", "KY, SCRANTON");
      zipCityState.put("40324", "KY, GEORGETOWN");
      zipCityState.put("40327", "KY, GRATZ");
      zipCityState.put("40328", "KY, GRAVEL SWITCH");
      zipCityState.put("40330", "KY, CORNISHVILLE");
      zipCityState.put("40336", "KY, JINKS");
      zipCityState.put("40337", "KY, JEFFERSONVILLE");
      zipCityState.put("40339", "KY, KEENE");
      zipCityState.put("40341", "KY, LAMERO");
      zipCityState.put("40342", "KY, LAWRENCEBURG");
      zipCityState.put("40345", "KY, MARIBA");
      zipCityState.put("40346", "KY, MEANS");
      zipCityState.put("40347", "KY, MIDWAY");
      zipCityState.put("40350", "KY, MOOREFIELD");
      zipCityState.put("40351", "KY, MOREHEAD");
      zipCityState.put("40353", "KY, MOUNT STERLING");
      zipCityState.put("40355", "KY, NEW LIBERTY");
      zipCityState.put("40356", "KY, NICHOLASVILLE");
      zipCityState.put("40358", "KY, OLYMPIA");
      zipCityState.put("40359", "KY, OWENTON");
      zipCityState.put("40360", "KY, OWINGSVILLE");
      zipCityState.put("40361", "KY, PARIS");
      zipCityState.put("40365", "KY, POMEROYTON");
      zipCityState.put("40370", "KY, SADIEVILLE");
      zipCityState.put("40371", "KY, SALT LICK");
      zipCityState.put("40372", "KY, BONDVILLE");
      zipCityState.put("40374", "KY, SHARPSBURG");
      zipCityState.put("40376", "KY, SLADE");
      zipCityState.put("40379", "KY, STAMPING GROUND");
      zipCityState.put("40380", "KY, PATSEY");
      zipCityState.put("40383", "KY, VERSAILLES");
      zipCityState.put("40385", "KY, BYBEE");
      zipCityState.put("40387", "KY, KOREA");
      zipCityState.put("40390", "KY, HIGH BRIDGE");
      zipCityState.put("40391", "KY, WINCHESTER");
      zipCityState.put("40402", "KY, MOORES CREEK");
      zipCityState.put("40403", "KY, BEREA");
      zipCityState.put("40409", "KY, BRODHEAD");
      zipCityState.put("40415", "KY, COBHILL");
      zipCityState.put("40417", "KY, CONWAY");
      zipCityState.put("40419", "KY, CRAB ORCHARD");
      zipCityState.put("40422", "KY, DANVILLE");
      zipCityState.put("40426", "KY, DREYFUS");
      zipCityState.put("40437", "KY, HUSTONVILLE");
      zipCityState.put("40440", "KY, JUNCTION CITY");
      zipCityState.put("40442", "KY, KINGS MOUNTAIN");
      zipCityState.put("40444", "KY, LANCASTER");
      zipCityState.put("40445", "KY, LIVINGSTON");
      zipCityState.put("40447", "KY, CLOVER BOTTOM");
      zipCityState.put("40456", "KY, CLIMAX");
      zipCityState.put("40460", "KY, ORLANDO");
      zipCityState.put("40461", "KY, PAINT LICK");
      zipCityState.put("40464", "KY, PARKSVILLE");
      zipCityState.put("40468", "KY, PERRYVILLE");
      zipCityState.put("40471", "KY, PRYSE");
      zipCityState.put("40472", "KY, RAVENNA");
      zipCityState.put("40475", "KY, RICHMOND");
      zipCityState.put("40481", "KY, SANDGAP");
      zipCityState.put("40484", "KY, STANFORD");
      zipCityState.put("40486", "KY, ELIAS");
      zipCityState.put("40489", "KY, WAYNESBURG");
      zipCityState.put("40502", "KY, LEXINGTON");
      zipCityState.put("40503", "KY, LEXINGTON");
      zipCityState.put("40504", "KY, LEXINGTON");
      zipCityState.put("40505", "KY, LEXINGTON");
      zipCityState.put("40507", "KY, LEXINGTON");
      zipCityState.put("40508", "KY, LEXINGTON");
      zipCityState.put("40509", "KY, LEXINGTON");
      zipCityState.put("40510", "KY, LEXINGTON");
      zipCityState.put("40511", "KY, LEXINGTON");
      zipCityState.put("40513", "KY, LEXINGTON");
      zipCityState.put("40514", "KY, LEXINGTON");
      zipCityState.put("40515", "KY, LEXINGTON");
      zipCityState.put("40516", "KY, LEXINGTON");
      zipCityState.put("40517", "KY, LEXINGTON");
      zipCityState.put("40601", "KY, HATTON");
      zipCityState.put("40701", "KY, CORBIN");
      zipCityState.put("40724", "KY, BUSH");
      zipCityState.put("40729", "KY, SYMBOL");
      zipCityState.put("40734", "KY, GRAY");
      zipCityState.put("40737", "KY, KEAVY");
      zipCityState.put("40740", "KY, LILY");
      zipCityState.put("40741", "KY, SASSER");
      zipCityState.put("40754", "KY, NEVISDALE");
      zipCityState.put("40759", "KY, ROCKHOLDS");
      zipCityState.put("40763", "KY, SILER");
      zipCityState.put("40769", "KY, PLEASANT VIEW");
      zipCityState.put("40771", "KY, WOODBINE");
      zipCityState.put("40801", "KY, AGES BROOKSIDE");
      zipCityState.put("40806", "KY, BAXTER");
      zipCityState.put("40807", "KY, BENHAM");
      zipCityState.put("40808", "KY, BIG LAUREL");
      zipCityState.put("40810", "KY, LEWIS CREEK");
      zipCityState.put("40813", "KY, CALVIN");
      zipCityState.put("40815", "KY, CRUMMIES");
      zipCityState.put("40817", "KY, 40817");
      zipCityState.put("40818", "KY, COALGOOD");
      zipCityState.put("40819", "KY, COLDIRON");
      zipCityState.put("40820", "KY, CRANKS");
      zipCityState.put("40823", "KY, CUMBERLAND");
      zipCityState.put("40824", "KY, DAYHOIT");
      zipCityState.put("40825", "KY, DIZNEY");
      zipCityState.put("40826", "KY, EOLIA");
      zipCityState.put("40828", "KY, LOUELLEN");
      zipCityState.put("40829", "KY, GRAYS KNOB");
      zipCityState.put("40830", "KY, GULSTON");
      zipCityState.put("40831", "KY, CHEVROLET");
      zipCityState.put("40843", "KY, HOLMES MILL");
      zipCityState.put("40845", "KY, HULEN");
      zipCityState.put("40846", "KY, KEITH");
      zipCityState.put("40847", "KY, KENVIR");
      zipCityState.put("40849", "KY, LEJUNIOR");
      zipCityState.put("40855", "KY, LYNCH");
      zipCityState.put("40858", "KY, MOZELLE");
      zipCityState.put("40861", "KY, OVEN FORK");
      zipCityState.put("40862", "KY, PARTRIDGE");
      zipCityState.put("40863", "KY, PATHFORK");
      zipCityState.put("40865", "KY, PUTNEY");
      zipCityState.put("40867", "KY, SMITH");
      zipCityState.put("40868", "KY, STINNETT");
      zipCityState.put("40870", "KY, TOTZ");
      zipCityState.put("40873", "KY, WALLINS CREEK");
      zipCityState.put("40902", "KY, ARJAY");
      zipCityState.put("40903", "KY, ARTEMUS");
      zipCityState.put("40905", "KY, 40905");
      zipCityState.put("40906", "KY, BAILEY SWITCH");
      zipCityState.put("40913", "KY, BEVERLY");
      zipCityState.put("40914", "KY, BIG CREEK");
      zipCityState.put("40915", "KY, BIMBLE");
      zipCityState.put("40921", "KY, BRYANTS STORE");
      zipCityState.put("40923", "KY, CANNON");
      zipCityState.put("40927", "KY, CLOSPLINT");
      zipCityState.put("40930", "KY, DEWITT");
      zipCityState.put("40935", "KY, SALT GUM");
      zipCityState.put("40940", "KY, FONDE");
      zipCityState.put("40943", "KY, GIRDLER");
      zipCityState.put("40946", "KY, GREEN ROAD");
      zipCityState.put("40949", "KY, HEIDRICK");
      zipCityState.put("40953", "KY, HINKLE");
      zipCityState.put("40958", "KY, KETTLE ISLAND");
      zipCityState.put("40962", "KY, BRIGHT SHADE");
      zipCityState.put("40964", "KY, MARY ALICE");
      zipCityState.put("40965", "KY, MIDDLESBORO");
      zipCityState.put("40970", "KY, MILLS");
      zipCityState.put("40972", "KY, ONEIDA");
      zipCityState.put("40977", "KY, CALLAWAY");
      zipCityState.put("40979", "KY, ROARK");
      zipCityState.put("40980", "KY, 40980");
      zipCityState.put("40982", "KY, SCALF");
      zipCityState.put("40983", "KY, SEXTONS CREEK");
      zipCityState.put("40988", "KY, STONEY FORK");
      zipCityState.put("40995", "KY, TROSPER");
      zipCityState.put("40997", "KY, WALKER");
      zipCityState.put("40999", "KY, WOOLLUM");
      zipCityState.put("41001", "KY, ALEXANDRIA");
      zipCityState.put("41002", "KY, AUGUSTA");
      zipCityState.put("41003", "KY, BERRY");
      zipCityState.put("41004", "KY, BROOKSVILLE");
      zipCityState.put("41005", "KY, RABBIT HASH");
      zipCityState.put("41006", "KY, BUTLER");
      zipCityState.put("41007", "KY, CALIFORNIA");
      zipCityState.put("41008", "KY, CARROLLTON");
      zipCityState.put("41010", "KY, CORINTH");
      zipCityState.put("41011", "KY, COVINGTON");
      zipCityState.put("41014", "KY, ROUSE");
      zipCityState.put("41015", "KY, LATONIA");
      zipCityState.put("41016", "KY, LUDLOW");
      zipCityState.put("41017", "KY, DIXIE");
      zipCityState.put("41018", "KY, ERLANGER");
      zipCityState.put("41030", "KY, CRITTENDEN");
      zipCityState.put("41031", "KY, CYNTHIANA");
      zipCityState.put("41033", "KY, DEMOSSVILLE");
      zipCityState.put("41034", "KY, DOVER");
      zipCityState.put("41035", "KY, DRY RIDGE");
      zipCityState.put("41039", "KY, EWING");
      zipCityState.put("41040", "KY, FALMOUTH");
      zipCityState.put("41041", "KY, FLEMINGSBURG");
      zipCityState.put("41042", "KY, FLORENCE");
      zipCityState.put("41043", "KY, FOSTER");
      zipCityState.put("41044", "KY, GERMANTOWN");
      zipCityState.put("41045", "KY, GHENT");
      zipCityState.put("41046", "KY, GLENCOE");
      zipCityState.put("41048", "KY, HEBRON");
      zipCityState.put("41049", "KY, HILLSBORO");
      zipCityState.put("41051", "KY, INDEPENDENCE");
      zipCityState.put("41052", "KY, JONESVILLE");
      zipCityState.put("41055", "KY, MAYS LICK");
      zipCityState.put("41056", "KY, LIMESTONE SQ");
      zipCityState.put("41059", "KY, MELBOURNE");
      zipCityState.put("41063", "KY, MORNING VIEW");
      zipCityState.put("41064", "KY, MOUNT OLIVET");
      zipCityState.put("41071", "KY, SOUTHGATE");
      zipCityState.put("41073", "KY, BELLEVUE");
      zipCityState.put("41074", "KY, DAYTON");
      zipCityState.put("41075", "KY, FORT THOMAS");
      zipCityState.put("41076", "KY, NEWPORT");
      zipCityState.put("41080", "KY, PETERSBURG");
      zipCityState.put("41083", "KY, SANDERS");
      zipCityState.put("41085", "KY, SILVER GROVE");
      zipCityState.put("41086", "KY, SPARTA");
      zipCityState.put("41091", "KY, UNION");
      zipCityState.put("41092", "KY, VERONA");
      zipCityState.put("41093", "KY, WALLINGFORD");
      zipCityState.put("41094", "KY, WALTON");
      zipCityState.put("41095", "KY, WARSAW");
      zipCityState.put("41097", "KY, WILLIAMSTOWN");
      zipCityState.put("41098", "KY, WORTHVILLE");
      zipCityState.put("41101", "KY, WESTWOOD");
      zipCityState.put("41102", "KY, ASHLAND");
      zipCityState.put("41121", "KY, ARGILLITE");
      zipCityState.put("41124", "KY, BLAINE");
      zipCityState.put("41127", "KY, CAMP DIX");
      zipCityState.put("41129", "KY, CATLETTSBURG");
      zipCityState.put("41132", "KY, DENTON");
      zipCityState.put("41135", "KY, HEAD OF GRASSY");
      zipCityState.put("41137", "KY, FIREBRICK");
      zipCityState.put("41139", "KY, FLATWOODS");
      zipCityState.put("41141", "KY, GARRISON");
      zipCityState.put("41143", "KY, FULTZ");
      zipCityState.put("41144", "KY, LYNN");
      zipCityState.put("41146", "KY, HITCHINS");
      zipCityState.put("41149", "KY, ISONVILLE");
      zipCityState.put("41159", "KY, MARTHA");
      zipCityState.put("41163", "KY, OLDTOWN");
      zipCityState.put("41164", "KY, LAWTON");
      zipCityState.put("41166", "KY, QUINCY");
      zipCityState.put("41168", "KY, RUSH");
      zipCityState.put("41169", "KY, RACELAND");
      zipCityState.put("41170", "KY, SAINT PAUL");
      zipCityState.put("41171", "KY, BURKE");
      zipCityState.put("41174", "KY, SOUTH PORTSMOUTH");
      zipCityState.put("41175", "KY, MALONETON");
      zipCityState.put("41177", "KY, STEPHENS");
      zipCityState.put("41178", "KY, 41178");
      zipCityState.put("41179", "KY, TRINITY");
      zipCityState.put("41180", "KY, WEBBVILLE");
      zipCityState.put("41183", "KY, WORTHINGTON");
      zipCityState.put("41189", "KY, TOLLESBORO");
      zipCityState.put("41201", "KY, ADAMS");
      zipCityState.put("41204", "KY, BOONS CAMP");
      zipCityState.put("41214", "KY, DAVELLA");
      zipCityState.put("41215", "KY, DENVER");
      zipCityState.put("41216", "KY, EAST POINT");
      zipCityState.put("41219", "KY, ELNA");
      zipCityState.put("41220", "KY, FUGET");
      zipCityState.put("41222", "KY, HAGERHILL");
      zipCityState.put("41224", "KY, JOB");
      zipCityState.put("41225", "KY, 41225");
      zipCityState.put("41226", "KY, KEATON");
      zipCityState.put("41228", "KY, LEANDER");
      zipCityState.put("41230", "KY, CLIFFORD");
      zipCityState.put("41231", "KY, LOVELY");
      zipCityState.put("41234", "KY, MEALLY");
      zipCityState.put("41237", "KY, OFFUTT");
      zipCityState.put("41238", "KY, MANILA");
      zipCityState.put("41240", "KY, NIPPA");
      zipCityState.put("41250", "KY, LAURA");
      zipCityState.put("41254", "KY, RIVER");
      zipCityState.put("41255", "KY, SITKA");
      zipCityState.put("41256", "KY, BARNETTS CREEK");
      zipCityState.put("41257", "KY, STAMBAUGH");
      zipCityState.put("41258", "KY, RICEVILLE");
      zipCityState.put("41260", "KY, THELMA");
      zipCityState.put("41262", "KY, DAVISPORT");
      zipCityState.put("41263", "KY, TUTOR KEY");
      zipCityState.put("41265", "KY, VAN LEAR");
      zipCityState.put("41266", "KY, FUGET");
      zipCityState.put("41267", "KY, HODE");
      zipCityState.put("41269", "KY, WHITEHOUSE");
      zipCityState.put("41271", "KY, WILLIAMSPORT");
      zipCityState.put("41274", "KY, WITTENSVILLE");
      zipCityState.put("41301", "KY, FLAT");
      zipCityState.put("41306", "KY, ALTRO");
      zipCityState.put("41311", "KY, VADA");
      zipCityState.put("41314", "KY, MORRIS FORK");
      zipCityState.put("41315", "KY, BURKHART");
      zipCityState.put("41316", "KY, 41316");
      zipCityState.put("41317", "KY, CLAYHOLE");
      zipCityState.put("41321", "KY, DECOY");
      zipCityState.put("41327", "KY, GILLMORE");
      zipCityState.put("41328", "KY, GREEN HALL");
      zipCityState.put("41331", "KY, HADDIX");
      zipCityState.put("41332", "KY, GRASSY CREEK");
      zipCityState.put("41338", "KY, ISLAND CITY");
      zipCityState.put("41339", "KY, CANOE");
      zipCityState.put("41340", "KY, LAMBRIC");
      zipCityState.put("41342", "KY, LEE CITY");
      zipCityState.put("41343", "KY, LEECO");
      zipCityState.put("41346", "KY, LITTLE");
      zipCityState.put("41348", "KY, HARDSHELL");
      zipCityState.put("41351", "KY, MISTLETOE");
      zipCityState.put("41357", "KY, NOCTOR");
      zipCityState.put("41358", "KY, OLD LANDING");
      zipCityState.put("41359", "KY, 41359");
      zipCityState.put("41360", "KY, PINE RIDGE");
      zipCityState.put("41363", "KY, QUICKSAND");
      zipCityState.put("41364", "KY, RICETOWN");
      zipCityState.put("41365", "KY, ROGERS");
      zipCityState.put("41366", "KY, ROUSSEAU");
      zipCityState.put("41367", "KY, ROWDY");
      zipCityState.put("41369", "KY, SALDEE");
      zipCityState.put("41370", "KY, 41370");
      zipCityState.put("41377", "KY, TALBERT");
      zipCityState.put("41385", "KY, VANCLEVE");
      zipCityState.put("41386", "KY, VINCENT");
      zipCityState.put("41390", "KY, WHICK");
      zipCityState.put("41393", "KY, 41393");
      zipCityState.put("41396", "KY, ZACHARIAH");
      zipCityState.put("41397", "KY, ZOE");
      zipCityState.put("41401", "KY, 41401");
      zipCityState.put("41407", "KY, CANEY");
      zipCityState.put("41409", "KY, CARVER");
      zipCityState.put("41412", "KY, COTTLE");
      zipCityState.put("41419", "KY, EDNA");
      zipCityState.put("41421", "KY, ELKFORK");
      zipCityState.put("41422", "KY, ELSIE");
      zipCityState.put("41425", "KY, EZEL");
      zipCityState.put("41429", "KY, 41429");
      zipCityState.put("41431", "KY, 41431");
      zipCityState.put("41441", "KY, HENDRICKS");
      zipCityState.put("41447", "KY, LENOX");
      zipCityState.put("41464", "KY, ROYALTON");
      zipCityState.put("41465", "KY, BETHANNA");
      zipCityState.put("41466", "KY, SEITZ");
      zipCityState.put("41472", "KY, BLAIRS MILL");
      zipCityState.put("41474", "KY, WHITE OAK");
      zipCityState.put("41501", "KY, BROAD BOTTOM");
      zipCityState.put("41503", "KY, SOUTH WILLIAMSON");
      zipCityState.put("41512", "KY, ASHCAMP");
      zipCityState.put("41513", "KY, BELCHER");
      zipCityState.put("41514", "KY, BELFRY");
      zipCityState.put("41519", "KY, CANADA");
      zipCityState.put("41522", "KY, SENTERVILLE");
      zipCityState.put("41524", "KY, BIGGS");
      zipCityState.put("41527", "KY, FOREST HILLS");
      zipCityState.put("41528", "KY, FREEBURN");
      zipCityState.put("41529", "KY, AFLEX");
      zipCityState.put("41531", "KY, HARDY");
      zipCityState.put("41535", "KY, HUDDY");
      zipCityState.put("41536", "KY, JAMBOREE");
      zipCityState.put("41537", "KY, PAYNE GAP");
      zipCityState.put("41539", "KY, KIMPER");
      zipCityState.put("41540", "KY, LICK CREEK");
      zipCityState.put("41543", "KY, MC ANDREWS");
      zipCityState.put("41544", "KY, MC CARR");
      zipCityState.put("41545", "KY, MC COMBS");
      zipCityState.put("41546", "KY, MC VEIGH");
      zipCityState.put("41548", "KY, MOUTHCARD");
      zipCityState.put("41551", "KY, PAW PAW");
      zipCityState.put("41553", "KY, PHELPS");
      zipCityState.put("41554", "KY, PHYLLIS");
      zipCityState.put("41555", "KY, PINSONFORK");
      zipCityState.put("41557", "KY, FISHTRAP");
      zipCityState.put("41559", "KY, REGINA");
      zipCityState.put("41560", "KY, ROBINSON CREEK");
      zipCityState.put("41562", "KY, SHELBIANA");
      zipCityState.put("41563", "KY, SHELBY GAP");
      zipCityState.put("41564", "KY, SIDNEY");
      zipCityState.put("41565", "KY, SPEIGHT");
      zipCityState.put("41566", "KY, STEELE");
      zipCityState.put("41567", "KY, STONE");
      zipCityState.put("41568", "KY, ARGO");
      zipCityState.put("41570", "KY, TURKEY CREEK");
      zipCityState.put("41571", "KY, VARNEY");
      zipCityState.put("41572", "KY, ETTY");
      zipCityState.put("41601", "KY, ALLEN");
      zipCityState.put("41602", "KY, AUXIER");
      zipCityState.put("41603", "KY, BANNER");
      zipCityState.put("41604", "KY, LIGON");
      zipCityState.put("41605", "KY, BETSY LAYNE");
      zipCityState.put("41606", "KY, BEVINSVILLE");
      zipCityState.put("41607", "KY, BLUE RIVER");
      zipCityState.put("41614", "KY, CRAYNOR");
      zipCityState.put("41615", "KY, DANA");
      zipCityState.put("41616", "KY, DAVID");
      zipCityState.put("41622", "KY, EASTERN");
      zipCityState.put("41626", "KY, ENDICOTT");
      zipCityState.put("41627", "KY, ESTILL");
      zipCityState.put("41629", "KY, GALVESTON");
      zipCityState.put("41630", "KY, GARRETT");
      zipCityState.put("41631", "KY, GRETHEL");
      zipCityState.put("41632", "KY, WALDO");
      zipCityState.put("41633", "KY, HALO");
      zipCityState.put("41635", "KY, HAROLD");
      zipCityState.put("41636", "KY, BUCKINGHAM");
      zipCityState.put("41637", "KY, PYRMID");
      zipCityState.put("41639", "KY, HONAKER");
      zipCityState.put("41640", "KY, ELMROCK");
      zipCityState.put("41642", "KY, IVEL");
      zipCityState.put("41643", "KY, LACKEY");
      zipCityState.put("41645", "KY, LANGLEY");
      zipCityState.put("41647", "KY, EAST MC DOWELL");
      zipCityState.put("41648", "KY, 41648");
      zipCityState.put("41649", "KY, HITE");
      zipCityState.put("41653", "KY, EMMA");
      zipCityState.put("41655", "KY, PRINTER");
      zipCityState.put("41659", "KY, STANVILLE");
      zipCityState.put("41660", "KY, TEABERRY");
      zipCityState.put("41666", "KY, WAYLAND");
      zipCityState.put("41701", "KY, DARFORK");
      zipCityState.put("41712", "KY, ARY");
      zipCityState.put("41714", "KY, BEAR BRANCH");
      zipCityState.put("41719", "KY, BLUE DIAMOND");
      zipCityState.put("41721", "KY, BUCKHORN");
      zipCityState.put("41722", "KY, TRIBBEY");
      zipCityState.put("41723", "KY, BUSY");
      zipCityState.put("41725", "KY, CARRIE");
      zipCityState.put("41727", "KY, CHAVIES");
      zipCityState.put("41728", "KY, CINDA");
      zipCityState.put("41729", "KY, COMBS");
      zipCityState.put("41730", "KY, CONFLUENCE");
      zipCityState.put("41731", "KY, ULVAH");
      zipCityState.put("41732", "KY, CUTSHIN");
      zipCityState.put("41733", "KY, DAISY");
      zipCityState.put("41735", "KY, DELPHIA");
      zipCityState.put("41736", "KY, DICE");
      zipCityState.put("41740", "KY, BEARVILLE");
      zipCityState.put("41743", "KY, FISTY");
      zipCityState.put("41745", "KY, GAYS CREEK");
      zipCityState.put("41746", "KY, HAPPY");
      zipCityState.put("41749", "KY, DRYHILL");
      zipCityState.put("41754", "KY, NAPFOR");
      zipCityState.put("41756", "KY, LEATHERWOOD");
      zipCityState.put("41759", "KY, ANCO");
      zipCityState.put("41760", "KY, SCUDDY");
      zipCityState.put("41763", "KY, SLEMP");
      zipCityState.put("41764", "KY, SMILAX");
      zipCityState.put("41765", "KY, TALCUM");
      zipCityState.put("41772", "KY, VEST");
      zipCityState.put("41773", "KY, VICCO");
      zipCityState.put("41774", "KY, FARLER");
      zipCityState.put("41775", "KY, WENDOVER");
      zipCityState.put("41776", "KY, FREW");
      zipCityState.put("41777", "KY, BIG ROCK");
      zipCityState.put("41801", "KY, AMBURGEY");
      zipCityState.put("41804", "KY, CARCASSONNE");
      zipCityState.put("41805", "KY, BRINKLEY");
      zipCityState.put("41811", "KY, CROWN");
      zipCityState.put("41812", "KY, DEANE");
      zipCityState.put("41815", "KY, ERMINE");
      zipCityState.put("41817", "KY, LARKSLANE");
      zipCityState.put("41819", "KY, GILLY");
      zipCityState.put("41821", "KY, SKYLINE");
      zipCityState.put("41822", "KY, HINDMAN");
      zipCityState.put("41823", "KY, HOLLYBUSH");
      zipCityState.put("41824", "KY, ISOM");
      zipCityState.put("41825", "KY, JACKHORN");
      zipCityState.put("41826", "KY, JEREMIAH");
      zipCityState.put("41828", "KY, PUNCHEON");
      zipCityState.put("41829", "KY, KONA");
      zipCityState.put("41831", "KY, SOFT SHELL");
      zipCityState.put("41832", "KY, LETCHER");
      zipCityState.put("41833", "KY, LINEFORK");
      zipCityState.put("41834", "KY, LITTCARR");
      zipCityState.put("41836", "KY, MALLIE");
      zipCityState.put("41838", "KY, MILLSTONE");
      zipCityState.put("41839", "KY, MOUSIE");
      zipCityState.put("41840", "KY, FLEMING NEON");
      zipCityState.put("41843", "KY, OMAHA");
      zipCityState.put("41844", "KY, RAVEN");
      zipCityState.put("41845", "KY, PREMIUM");
      zipCityState.put("41847", "KY, REDFOX");
      zipCityState.put("41848", "KY, ROXANA");
      zipCityState.put("41849", "KY, SECO");
      zipCityState.put("41855", "KY, THORNTON");
      zipCityState.put("41858", "KY, DAY RURAL");
      zipCityState.put("41859", "KY, DEMA");
      zipCityState.put("41861", "KY, RAVEN");
      zipCityState.put("41862", "KY, DRY CREEK");
      zipCityState.put("42001", "KY, PADUCAH");
      zipCityState.put("42003", "KY, PADUCAH");
      zipCityState.put("42020", "KY, ALMO");
      zipCityState.put("42021", "KY, ARLINGTON");
      zipCityState.put("42023", "KY, BARDWELL");
      zipCityState.put("42024", "KY, BARLOW");
      zipCityState.put("42025", "KY, BENTON");
      zipCityState.put("42027", "KY, BOAZ");
      zipCityState.put("42028", "KY, BURNA");
      zipCityState.put("42029", "KY, CALVERT CITY");
      zipCityState.put("42031", "KY, CLINTON");
      zipCityState.put("42032", "KY, COLUMBUS");
      zipCityState.put("42035", "KY, CUNNINGHAM");
      zipCityState.put("42036", "KY, DEXTER");
      zipCityState.put("42038", "KY, EDDYVILLE");
      zipCityState.put("42039", "KY, FANCY FARM");
      zipCityState.put("42040", "KY, FARMINGTON");
      zipCityState.put("42041", "KY, CRUTCHFIELD");
      zipCityState.put("42044", "KY, GILBERTSVILLE");
      zipCityState.put("42045", "KY, IUKA");
      zipCityState.put("42047", "KY, HAMPTON");
      zipCityState.put("42048", "KY, HARDIN");
      zipCityState.put("42049", "KY, HAZEL");
      zipCityState.put("42050", "KY, HICKMAN");
      zipCityState.put("42051", "KY, HICKORY");
      zipCityState.put("42053", "KY, KEVIL");
      zipCityState.put("42054", "KY, KIRKSEY");
      zipCityState.put("42055", "KY, KUTTAWA");
      zipCityState.put("42056", "KY, LA CENTER");
      zipCityState.put("42058", "KY, LEDBETTER");
      zipCityState.put("42064", "KY, MARION");
      zipCityState.put("42066", "KY, MAYFIELD");
      zipCityState.put("42069", "KY, MELBER");
      zipCityState.put("42071", "KY, MURRAY");
      zipCityState.put("42076", "KY, NEW CONCORD");
      zipCityState.put("42078", "KY, SALEM");
      zipCityState.put("42079", "KY, SEDALIA");
      zipCityState.put("42081", "KY, CARRSVILLE");
      zipCityState.put("42082", "KY, SYMSONIA");
      zipCityState.put("42083", "KY, TILINE");
      zipCityState.put("42085", "KY, WATER VALLEY");
      zipCityState.put("42086", "KY, WEST PADUCAH");
      zipCityState.put("42087", "KY, WICKLIFFE");
      zipCityState.put("42088", "KY, WINGO");
      zipCityState.put("42101", "KY, PLUM SPRINGS");
      zipCityState.put("42103", "KY, BOWLING GREEN");
      zipCityState.put("42104", "KY, BOWLING GREEN");
      zipCityState.put("42120", "KY, ADOLPHUS");
      zipCityState.put("42122", "KY, ALVATON");
      zipCityState.put("42123", "KY, AUSTIN");
      zipCityState.put("42124", "KY, BEAUMONT");
      zipCityState.put("42127", "KY, CAVE CITY");
      zipCityState.put("42129", "KY, SUBTLE");
      zipCityState.put("42130", "KY, EIGHTY EIGHT");
      zipCityState.put("42131", "KY, ETOILE");
      zipCityState.put("42133", "KY, FOUNTAIN RUN");
      zipCityState.put("42134", "KY, FRANKLIN");
      zipCityState.put("42140", "KY, GAMALIEL");
      zipCityState.put("42141", "KY, GLASGOW");
      zipCityState.put("42151", "KY, HESTAND");
      zipCityState.put("42153", "KY, HOLLAND");
      zipCityState.put("42154", "KY, KNOB LICK");
      zipCityState.put("42155", "KY, LAMB");
      zipCityState.put("42156", "KY, LUCAS");
      zipCityState.put("42157", "KY, MOUNT HERMAN");
      zipCityState.put("42159", "KY, OAKLAND");
      zipCityState.put("42160", "KY, PARK CITY");
      zipCityState.put("42163", "KY, ROCKY HILL");
      zipCityState.put("42164", "KY, SCOTTSVILLE");
      zipCityState.put("42166", "KY, SUMMER SHADE");
      zipCityState.put("42167", "KY, T VILLE");
      zipCityState.put("42169", "KY, WILLOW SHADE");
      zipCityState.put("42170", "KY, WOODBURN");
      zipCityState.put("42171", "KY, SMITHS GROVE");
      zipCityState.put("42202", "KY, ADAIRVILLE");
      zipCityState.put("42204", "KY, ALLENSVILLE");
      zipCityState.put("42206", "KY, AUBURN");
      zipCityState.put("42207", "KY, BEE SPRING");
      zipCityState.put("42210", "KY, REEDYVILLE");
      zipCityState.put("42211", "KY, GOLDEN POND");
      zipCityState.put("42214", "KY, CENTER");
      zipCityState.put("42215", "KY, CERULEAN");
      zipCityState.put("42217", "KY, CROFTON");
      zipCityState.put("42220", "KY, ELKTON");
      zipCityState.put("42223", "KY, FORT CAMPBELL");
      zipCityState.put("42232", "KY, GRACEY");
      zipCityState.put("42234", "KY, TINY TOWN");
      zipCityState.put("42236", "KY, HERNDON");
      zipCityState.put("42240", "KY, HOPKINSVILLE");
      zipCityState.put("42250", "KY, HUFF");
      zipCityState.put("42252", "KY, JETSON");
      zipCityState.put("42254", "KY, LA FAYETTE");
      zipCityState.put("42256", "KY, LEWISBURG");
      zipCityState.put("42257", "KY, LINDSEYVILLE");
      zipCityState.put("42259", "KY, MAMMOTH CAVE NAT");
      zipCityState.put("42261", "KY, LOGANSPORT");
      zipCityState.put("42262", "KY, OAK GROVE");
      zipCityState.put("42265", "KY, OLMSTEAD");
      zipCityState.put("42266", "KY, PEMBROKE");
      zipCityState.put("42268", "KY, QUALITY");
      zipCityState.put("42273", "KY, ROCHESTER");
      zipCityState.put("42274", "KY, BROWNING");
      zipCityState.put("42275", "KY, ROUNDHILL");
      zipCityState.put("42276", "KY, DAYSVILLE");
      zipCityState.put("42280", "KY, SHARON GROVE");
      zipCityState.put("42284", "KY, SUNFISH");
      zipCityState.put("42285", "KY, KYROCK");
      zipCityState.put("42286", "KY, TRENTON");
      zipCityState.put("42287", "KY, WELCHS CREEK");
      zipCityState.put("42301", "KY, OWENSBORO");
      zipCityState.put("42303", "KY, OWENSBORO");
      zipCityState.put("42320", "KY, BEAVER DAM");
      zipCityState.put("42321", "KY, BEECH CREEK");
      zipCityState.put("42323", "KY, BEECHMONT");
      zipCityState.put("42324", "KY, BELTON");
      zipCityState.put("42325", "KY, BREMEN");
      zipCityState.put("42326", "KY, BROWDER");
      zipCityState.put("42327", "KY, CALHOUN");
      zipCityState.put("42328", "KY, CENTERTOWN");
      zipCityState.put("42330", "KY, CENTRAL CITY");
      zipCityState.put("42333", "KY, CROMWELL");
      zipCityState.put("42337", "KY, DRAKESBORO");
      zipCityState.put("42338", "KY, DUNDEE");
      zipCityState.put("42339", "KY, DUNMOR");
      zipCityState.put("42340", "KY, 42340");
      zipCityState.put("42343", "KY, FORDSVILLE");
      zipCityState.put("42344", "KY, GRAHAM");
      zipCityState.put("42345", "KY, GREENVILLE");
      zipCityState.put("42347", "KY, HARTFORD");
      zipCityState.put("42348", "KY, HAWESVILLE");
      zipCityState.put("42349", "KY, HORSE BRANCH");
      zipCityState.put("42350", "KY, ISLAND");
      zipCityState.put("42351", "KY, LEWISPORT");
      zipCityState.put("42352", "KY, LIVERMORE");
      zipCityState.put("42355", "KY, MACEO");
      zipCityState.put("42358", "KY, NARROWS");
      zipCityState.put("42361", "KY, OLATON");
      zipCityState.put("42365", "KY, PENROD");
      zipCityState.put("42366", "KY, PHILPOT");
      zipCityState.put("42368", "KY, REYNOLDS STATION");
      zipCityState.put("42369", "KY, ROCKPORT");
      zipCityState.put("42371", "KY, RUMSEY");
      zipCityState.put("42372", "KY, SACRAMENTO");
      zipCityState.put("42376", "KY, UTICA");
      zipCityState.put("42378", "KY, WHITESVILLE");
      zipCityState.put("42404", "KY, CLAY");
      zipCityState.put("42406", "KY, CORYDON");
      zipCityState.put("42408", "KY, DAWSON SPRINGS");
      zipCityState.put("42409", "KY, DIXON");
      zipCityState.put("42410", "KY, EARLINGTON");
      zipCityState.put("42411", "KY, FREDONIA");
      zipCityState.put("42413", "KY, HANSON");
      zipCityState.put("42420", "KY, HENDERSON");
      zipCityState.put("42431", "KY, MADISONVILLE");
      zipCityState.put("42436", "KY, MANITOU");
      zipCityState.put("42437", "KY, HENSHAW");
      zipCityState.put("42441", "KY, NEBO");
      zipCityState.put("42442", "KY, NORTONVILLE");
      zipCityState.put("42445", "KY, PRINCETON");
      zipCityState.put("42450", "KY, PROVIDENCE");
      zipCityState.put("42451", "KY, REED");
      zipCityState.put("42452", "KY, ROBARDS");
      zipCityState.put("42453", "KY, SAINT CHARLES");
      zipCityState.put("42455", "KY, SEBREE");
      zipCityState.put("42456", "KY, SLAUGHTERS");
      zipCityState.put("42458", "KY, SPOTTSVILLE");
      zipCityState.put("42459", "KY, STURGIS");
      zipCityState.put("42461", "KY, UNIONTOWN");
      zipCityState.put("42462", "KY, WAVERLY");
      zipCityState.put("42464", "KY, WHITE PLAINS");
      zipCityState.put("42501", "KY, ALCALDE");
      zipCityState.put("42516", "KY, BETHELRIDGE");
      zipCityState.put("42518", "KY, BRONSTON");
      zipCityState.put("42519", "KY, SLOANS VALLEY");
      zipCityState.put("42528", "KY, DUNNVILLE");
      zipCityState.put("42532", "KY, JABEZ");
      zipCityState.put("42539", "KY, LIBERTY");
      zipCityState.put("42541", "KY, MIDDLEBURG");
      zipCityState.put("42544", "KY, POINTER");
      zipCityState.put("42553", "KY, SCIENCE HILL");
      zipCityState.put("42554", "KY, SHOPVILLE");
      zipCityState.put("42555", "KY, SLOANS VALLEY");
      zipCityState.put("42558", "KY, TATEVILLE");
      zipCityState.put("42566", "KY, YOSEMITE");
      zipCityState.put("42567", "KY, PULASKI");
      zipCityState.put("42601", "KY, AARON");
      zipCityState.put("42602", "KY, ALBANY");
      zipCityState.put("42603", "KY, ALPHA");
      zipCityState.put("42611", "KY, COOPERSVILLE");
      zipCityState.put("42613", "KY, DELTA");
      zipCityState.put("42629", "KY, JAMESTOWN");
      zipCityState.put("42633", "KY, PUEBLO");
      zipCityState.put("42634", "KY, PARKERS LAKE");
      zipCityState.put("42635", "KY, HOLLYHILL");
      zipCityState.put("42638", "KY, REVELO");
      zipCityState.put("42640", "KY, ROCKYBRANCH");
      zipCityState.put("42642", "KY, WEBBS CROSS ROAD");
      zipCityState.put("42643", "KY, SAWYER");
      zipCityState.put("42647", "KY, STEARNS");
      zipCityState.put("42649", "KY, STRUNK");
      zipCityState.put("42653", "KY, WIBORG");
      zipCityState.put("42655", "KY, WINDY");
      zipCityState.put("42701", "KY, E TOWN");
      zipCityState.put("42711", "KY, BAKERTON");
      zipCityState.put("42712", "KY, BIG CLIFTY");
      zipCityState.put("42713", "KY, BONNIEVILLE");
      zipCityState.put("42714", "KY, BOW");
      zipCityState.put("42715", "KY, BREEDING");
      zipCityState.put("42716", "KY, BUFFALO");
      zipCityState.put("42717", "KY, BURKESVILLE");
      zipCityState.put("42718", "KY, CAMPBELLSVILLE");
      zipCityState.put("42721", "KY, CANEYVILLE");
      zipCityState.put("42722", "KY, CANMER");
      zipCityState.put("42723", "KY, CASEY CREEK");
      zipCityState.put("42724", "KY, STEPHENSBURG");
      zipCityState.put("42726", "KY, WAX");
      zipCityState.put("42728", "KY, MONTPELIER");
      zipCityState.put("42729", "KY, CUB RUN");
      zipCityState.put("42730", "KY, CUNDIFF");
      zipCityState.put("42731", "KY, DUBRE");
      zipCityState.put("42732", "KY, E VIEW");
      zipCityState.put("42733", "KY, ELK HORN");
      zipCityState.put("42735", "KY, FAIRPLAY");
      zipCityState.put("42736", "KY, FINLEY");
      zipCityState.put("42740", "KY, GLENDALE");
      zipCityState.put("42741", "KY, GLENS FORK");
      zipCityState.put("42742", "KY, GRADYVILLE");
      zipCityState.put("42743", "KY, GREENSBURG");
      zipCityState.put("42746", "KY, HARDYVILLE");
      zipCityState.put("42748", "KY, HODGENVILLE");
      zipCityState.put("42749", "KY, HORSE CAVE");
      zipCityState.put("42752", "KY, KETTLE");
      zipCityState.put("42753", "KY, KNIFLEY");
      zipCityState.put("42754", "KY, SADLER");
      zipCityState.put("42757", "KY, MAGNOLIA");
      zipCityState.put("42761", "KY, MILLTOWN");
      zipCityState.put("42762", "KY, MILLWOOD");
      zipCityState.put("42764", "KY, MOUNT SHERMAN");
      zipCityState.put("42765", "KY, MUNFORDVILLE");
      zipCityState.put("42768", "KY, PEYTONSBURG");
      zipCityState.put("42776", "KY, SONORA");
      zipCityState.put("42782", "KY, SUMMERSVILLE");
      zipCityState.put("42784", "KY, UPTON");
      zipCityState.put("42788", "KY, WHITE MILLS");

      zipCityState.put("22001", "VA, ALDIE");
      zipCityState.put("22002", "VA, AMISSVILLE");
      zipCityState.put("22003", "VA, ANNANDALE");
      zipCityState.put("22010", "VA, ARCOLA");
      zipCityState.put("22011", "VA, ASHBURN");
      zipCityState.put("22012", "VA, BLUEMONT");
      zipCityState.put("22013", "VA, BRISTOW");
      zipCityState.put("22014", "VA, BROAD RUN");
      zipCityState.put("22015", "VA, BURKE");
      zipCityState.put("22018", "VA, CATHARPIN");
      zipCityState.put("22019", "VA, CATLETT");
      zipCityState.put("22020", "VA, CENTREVILLE");
      zipCityState.put("22021", "VA, CHANTILLY");
      zipCityState.put("22024", "VA, CLIFTON");
      zipCityState.put("22025", "VA, DELAPLANE");
      zipCityState.put("22026", "VA, DUMFRIES");
      zipCityState.put("22027", "VA, DUNN LORING");
      zipCityState.put("22030", "VA, BURKE");
      zipCityState.put("22031", "VA, FAIRFAX");
      zipCityState.put("22032", "VA, FAIRFAX");
      zipCityState.put("22033", "VA, FAIRFAX");
      zipCityState.put("22039", "VA, FAIRFAX STATION");
      zipCityState.put("22041", "VA, BAILEYS CROSSROA");
      zipCityState.put("22042", "VA, MOSBY");
      zipCityState.put("22043", "VA, PIMMIT");
      zipCityState.put("22044", "VA, SEVEN CORNERS");
      zipCityState.put("22046", "VA, FALLS CHURCH");
      zipCityState.put("22060", "VA, FORT BELVOIR");
      zipCityState.put("22065", "VA, GAINESVILLE");
      zipCityState.put("22066", "VA, GREAT FALLS");
      zipCityState.put("22068", "VA, HAMILTON");
      zipCityState.put("22069", "VA, HAYMARKET");
      zipCityState.put("22070", "VA, HERNDON");
      zipCityState.put("22071", "VA, HERNDON");
      zipCityState.put("22075", "VA, LEESBURG");
      zipCityState.put("22079", "VA, MASON NECK");
      zipCityState.put("22080", "VA, LOVETTSVILLE");
      zipCityState.put("22090", "VA, LAKE ANNE");
      zipCityState.put("22091", "VA, RESTON");
      zipCityState.put("22094", "VA, RESTON");
      zipCityState.put("22101", "VA, MC LEAN");
      zipCityState.put("22102", "VA, WEST MCLEAN");
      zipCityState.put("22110", "VA, MANASSAS");
      zipCityState.put("22111", "VA, MANASSAS PARK");
      zipCityState.put("22115", "VA, MARSHALL");
      zipCityState.put("22117", "VA, MIDDLEBURG");
      zipCityState.put("22123", "VA, NOKESVILLE");
      zipCityState.put("22124", "VA, OAKTON");
      zipCityState.put("22129", "VA, PAEONIAN SPRINGS");
      zipCityState.put("22130", "VA, PARIS");
      zipCityState.put("22132", "VA, HILLSBORO");
      zipCityState.put("22134", "VA, QUANTICO");
      zipCityState.put("22141", "VA, ROUND HILL");
      zipCityState.put("22150", "VA, SPRINGFIELD");
      zipCityState.put("22151", "VA, NORTH SPRINGFIEL");
      zipCityState.put("22152", "VA, WEST SPRINGFIELD");
      zipCityState.put("22153", "VA, SPRINGFIELD");
      zipCityState.put("22170", "VA, STERLING");
      zipCityState.put("22171", "VA, THE PLAINS");
      zipCityState.put("22172", "VA, TRIANGLE");
      zipCityState.put("22176", "VA, UPPERVILLE");
      zipCityState.put("22180", "VA, VIENNA");
      zipCityState.put("22181", "VA, VIENNA");
      zipCityState.put("22182", "VA, VIENNA");
      zipCityState.put("22186", "VA, AIRLIE");
      zipCityState.put("22190", "VA, WATERFORD");
      zipCityState.put("22191", "VA, WOODBRIDGE");
      zipCityState.put("22192", "VA, LAKERIDGE");
      zipCityState.put("22193", "VA, DALE CITY");
      zipCityState.put("22201", "VA, ARLINGTON");
      zipCityState.put("22202", "VA, ARLINGTON");
      zipCityState.put("22203", "VA, ARLINGTON");
      zipCityState.put("22204", "VA, ARLINGTON");
      zipCityState.put("22205", "VA, ARLINGTON");
      zipCityState.put("22206", "VA, ARLINGTON");
      zipCityState.put("22207", "VA, ARLINGTON");
      zipCityState.put("22209", "VA, ARLINGTON");
      zipCityState.put("22211", "VA, ARLINGTON");
      zipCityState.put("22213", "VA, ARLINGTON");
      zipCityState.put("22301", "VA, ALEXANDRIA");
      zipCityState.put("22302", "VA, ALEXANDRIA");
      zipCityState.put("22303", "VA, JEFFERSON MANOR");
      zipCityState.put("22304", "VA, ALEXANDRIA");
      zipCityState.put("22305", "VA, ALEXANDRIA");
      zipCityState.put("22306", "VA, COMMUNITY");
      zipCityState.put("22307", "VA, BELLE VIEW");
      zipCityState.put("22308", "VA, WELLINGTON");
      zipCityState.put("22309", "VA, ENGLESIDE");
      zipCityState.put("22310", "VA, FRANCONIA");
      zipCityState.put("22311", "VA, ALEXANDRIA");
      zipCityState.put("22312", "VA, ALEXANDRIA");
      zipCityState.put("22314", "VA, ALEXANDRIA");
      zipCityState.put("22401", "VA, FREDERICKSBURG");
      zipCityState.put("22405", "VA, FALMOUTH");
      zipCityState.put("22406", "VA, FREDERICKSBURG");
      zipCityState.put("22407", "VA, FREDERICKSBURG");
      zipCityState.put("22408", "VA, FREDERICKSBURG");
      zipCityState.put("22427", "VA, BOWLING GREEN");
      zipCityState.put("22432", "VA, BURGESS");
      zipCityState.put("22433", "VA, BURR HILL");
      zipCityState.put("22435", "VA, CALLAO");
      zipCityState.put("22436", "VA, CARET");
      zipCityState.put("22437", "VA, CENTER CROSS");
      zipCityState.put("22438", "VA, CHAMPLAIN");
      zipCityState.put("22439", "VA, CHANCE");
      zipCityState.put("22443", "VA, OAK GROVE");
      zipCityState.put("22448", "VA, DAHLGREN");
      zipCityState.put("22454", "VA, HOWERTONS");
      zipCityState.put("22460", "VA, FARNHAM");
      zipCityState.put("22469", "VA, HAGUE");
      zipCityState.put("22473", "VA, HEATHSVILLE");
      zipCityState.put("22476", "VA, HUSTLE");
      zipCityState.put("22480", "VA, IRVINGTON");
      zipCityState.put("22482", "VA, KILMARNOCK");
      zipCityState.put("22485", "VA, KING GEORGE");
      zipCityState.put("22488", "VA, KINSALE");
      zipCityState.put("22503", "VA, LANCASTER");
      zipCityState.put("22504", "VA, LANEVIEW");
      zipCityState.put("22508", "VA, LOCUST GROVE");
      zipCityState.put("22509", "VA, LORETTO");
      zipCityState.put("22511", "VA, LOTTSBURG");
      zipCityState.put("22514", "VA, MILFORD");
      zipCityState.put("22520", "VA, MONTROSS");
      zipCityState.put("22534", "VA, PARTLOW");
      zipCityState.put("22535", "VA, PORT ROYAL");
      zipCityState.put("22538", "VA, RAPPAHANNOCK ACA");
      zipCityState.put("22539", "VA, REEDVILLE");
      zipCityState.put("22542", "VA, RHOADESVILLE");
      zipCityState.put("22546", "VA, RUTHER GLEN");
      zipCityState.put("22553", "VA, SNELL");
      zipCityState.put("22554", "VA, STAFFORD");
      zipCityState.put("22559", "VA, SUPPLY");
      zipCityState.put("22560", "VA, TAPPAHANNOCK");
      zipCityState.put("22567", "VA, UNIONVILLE");
      zipCityState.put("22568", "VA, MINE RUN");
      zipCityState.put("22572", "VA, NOMINI GROVE");
      zipCityState.put("22576", "VA, WEEMS");
      zipCityState.put("22578", "VA, WINDMILL POINT");
      zipCityState.put("22579", "VA, WICOMICO CHURCH");
      zipCityState.put("22580", "VA, WOODFORD");
      zipCityState.put("22601", "VA, WINCHESTER");
      zipCityState.put("22610", "VA, BROWNTOWN");
      zipCityState.put("22611", "VA, BERRYVILLE");
      zipCityState.put("22620", "VA, BOYCE");
      zipCityState.put("22624", "VA, CLEAR BROOK");
      zipCityState.put("22625", "VA, WHITACRE");
      zipCityState.put("22627", "VA, FLINT HILL");
      zipCityState.put("22630", "VA, FRONT ROYAL");
      zipCityState.put("22637", "VA, GORE");
      zipCityState.put("22639", "VA, HUME");
      zipCityState.put("22640", "VA, HUNTLY");
      zipCityState.put("22641", "VA, LEBANON CHURCH");
      zipCityState.put("22642", "VA, LINDEN");
      zipCityState.put("22643", "VA, MARKHAM");
      zipCityState.put("22644", "VA, MAURERTOWN");
      zipCityState.put("22645", "VA, MIDDLETOWN");
      zipCityState.put("22649", "VA, RELIANCE");
      zipCityState.put("22650", "VA, RILEYVILLE");
      zipCityState.put("22652", "VA, SAINT DAVIDS CHU");
      zipCityState.put("22654", "VA, STAR TANNERY");
      zipCityState.put("22655", "VA, STEPHENS CITY");
      zipCityState.put("22656", "VA, STEPHENSON");
      zipCityState.put("22657", "VA, STRASBURG");
      zipCityState.put("22660", "VA, TOMS BROOK");
      zipCityState.put("22663", "VA, WHITE POST");
      zipCityState.put("22664", "VA, WOODSTOCK");
      zipCityState.put("22701", "VA, RACCOON FORD");
      zipCityState.put("22709", "VA, ARODA");
      zipCityState.put("22712", "VA, MORRISVILLE");
      zipCityState.put("22713", "VA, BOSTON");
      zipCityState.put("22714", "VA, BRANDY STATION");
      zipCityState.put("22715", "VA, BRIGHTWOOD");
      zipCityState.put("22716", "VA, CASTLETON");
      zipCityState.put("22718", "VA, ELKWOOD");
      zipCityState.put("22719", "VA, ETLAN");
      zipCityState.put("22720", "VA, GOLDVEIN");
      zipCityState.put("22722", "VA, HAYWOOD");
      zipCityState.put("22724", "VA, JEFFERSONTON");
      zipCityState.put("22725", "VA, LEON");
      zipCityState.put("22726", "VA, LIGNUM");
      zipCityState.put("22727", "VA, AYLOR");
      zipCityState.put("22728", "VA, MIDLAND");
      zipCityState.put("22729", "VA, MITCHELLS");
      zipCityState.put("22731", "VA, PRATTS");
      zipCityState.put("22732", "VA, RADIANT");
      zipCityState.put("22733", "VA, RAPIDAN");
      zipCityState.put("22734", "VA, REMINGTON");
      zipCityState.put("22735", "VA, REVA");
      zipCityState.put("22736", "VA, RICHARDSVILLE");
      zipCityState.put("22737", "VA, RIXEYVILLE");
      zipCityState.put("22738", "VA, UNO");
      zipCityState.put("22740", "VA, SPERRYVILLE");
      zipCityState.put("22741", "VA, STEVENSBURG");
      zipCityState.put("22742", "VA, SUMERDUCK");
      zipCityState.put("22743", "VA, SYRIA");
      zipCityState.put("22746", "VA, VIEWTOWN");
      zipCityState.put("22747", "VA, WASHINGTON");
      zipCityState.put("22749", "VA, WOODVILLE");
      zipCityState.put("22801", "VA, HARRISONBURG");
      zipCityState.put("22810", "VA, BASYE");
      zipCityState.put("22811", "VA, BERGTON");
      zipCityState.put("22812", "VA, BRIDGEWATER");
      zipCityState.put("22815", "VA, BROADWAY");
      zipCityState.put("22820", "VA, CRIDERS");
      zipCityState.put("22821", "VA, MONTEZUMA");
      zipCityState.put("22824", "VA, EDINBURG");
      zipCityState.put("22827", "VA, ELKTON");
      zipCityState.put("22830", "VA, FULKS RUN");
      zipCityState.put("22831", "VA, HINTON");
      zipCityState.put("22832", "VA, KEEZLETOWN");
      zipCityState.put("22834", "VA, LINVILLE");
      zipCityState.put("22835", "VA, LURAY");
      zipCityState.put("22840", "VA, MC GAHEYSVILLE");
      zipCityState.put("22841", "VA, MOUNT CRAWFORD");
      zipCityState.put("22842", "VA, CONICVILLE");
      zipCityState.put("22843", "VA, MOUNT SOLON");
      zipCityState.put("22844", "VA, NEW MARKET");
      zipCityState.put("22845", "VA, ORKNEY SPRINGS");
      zipCityState.put("22846", "VA, MONTEVIDEO");
      zipCityState.put("22847", "VA, SHENANDOAH CAVER");
      zipCityState.put("22849", "VA, SHENANDOAH");
      zipCityState.put("22851", "VA, STANLEY");
      zipCityState.put("22853", "VA, TIMBERVILLE");
      zipCityState.put("22901", "VA, CHARLOTTESVILLE");
      zipCityState.put("22903", "VA, UNIVERSITY");
      zipCityState.put("22920", "VA, AFTON");
      zipCityState.put("22922", "VA, TYE RIVER");
      zipCityState.put("22923", "VA, BURNLEYS");
      zipCityState.put("22929", "VA, COBHAM");
      zipCityState.put("22931", "VA, COVESVILLE");
      zipCityState.put("22932", "VA, YANCEY MILLS");
      zipCityState.put("22935", "VA, BOONESVILLE");
      zipCityState.put("22936", "VA, EARLYSVILLE");
      zipCityState.put("22937", "VA, ESMONT");
      zipCityState.put("22938", "VA, FABER");
      zipCityState.put("22939", "VA, WOODROW WILSON");
      zipCityState.put("22940", "VA, MISSION HOME");
      zipCityState.put("22942", "VA, CASHS CORNER");
      zipCityState.put("22943", "VA, GREENWOOD");
      zipCityState.put("22946", "VA, KEENE");
      zipCityState.put("22947", "VA, BOYD TAVERN");
      zipCityState.put("22948", "VA, LOCUST DALE");
      zipCityState.put("22949", "VA, LOVINGSTON");
      zipCityState.put("22951", "VA, LOWESVILLE");
      zipCityState.put("22952", "VA, SHERANDO");
      zipCityState.put("22958", "VA, WINTERGREEN");
      zipCityState.put("22959", "VA, ALBERENE");
      zipCityState.put("22960", "VA, MONTFORD");
      zipCityState.put("22963", "VA, BYBEE");
      zipCityState.put("22964", "VA, PINEY RIVER");
      zipCityState.put("22967", "VA, ROSELAND");
      zipCityState.put("22968", "VA, ADVANCE MILLS");
      zipCityState.put("22969", "VA, SCHUYLER");
      zipCityState.put("22971", "VA, ROCKFISH");
      zipCityState.put("22972", "VA, SOMERSET");
      zipCityState.put("22973", "VA, GEER");
      zipCityState.put("22974", "VA, TROY");
      zipCityState.put("22980", "VA, WAYNESBORO");
      zipCityState.put("23002", "VA, AMELIA COURT HOU");
      zipCityState.put("23004", "VA, ARVONIA");
      zipCityState.put("23005", "VA, ASHLAND");
      zipCityState.put("23009", "VA, AYLETT");
      zipCityState.put("23011", "VA, BARHAMSVILLE");
      zipCityState.put("23013", "VA, 23013");
      zipCityState.put("23015", "VA, BEAVERDAM");
      zipCityState.put("23016", "VA, BEAVERLETT");
      zipCityState.put("23020", "VA, 23020");
      zipCityState.put("23021", "VA, BOHANNON");
      zipCityState.put("23022", "VA, BREMO BLUFF");
      zipCityState.put("23023", "VA, BRUINGTON");
      zipCityState.put("23024", "VA, BUMPASS");
      zipCityState.put("23025", "VA, MILES");
      zipCityState.put("23027", "VA, TAMWORTH");
      zipCityState.put("23029", "VA, CAUTHORNVILLE");
      zipCityState.put("23030", "VA, CHARLES CITY");
      zipCityState.put("23032", "VA, CHURCH VIEW");
      zipCityState.put("23037", "VA, COLOGNE");
      zipCityState.put("23038", "VA, COLUMBIA");
      zipCityState.put("23039", "VA, CROZIER");
      zipCityState.put("23040", "VA, CUMBERLAND");
      zipCityState.put("23042", "VA, 23042");
      zipCityState.put("23043", "VA, DELTAVILLE");
      zipCityState.put("23045", "VA, DIGGS");
      zipCityState.put("23047", "VA, DOSWELL");
      zipCityState.put("23050", "VA, DUTTON");
      zipCityState.put("23055", "VA, FORK UNION");
      zipCityState.put("23060", "VA, GLEN ALLEN");
      zipCityState.put("23061", "VA, PINERO");
      zipCityState.put("23062", "VA, GLOUCESTER POINT");
      zipCityState.put("23063", "VA, GOOCHLAND");
      zipCityState.put("23065", "VA, GUM SPRING");
      zipCityState.put("23066", "VA, GWYNN");
      zipCityState.put("23069", "VA, HANOVER");
      zipCityState.put("23070", "VA, HARDYVILLE");
      zipCityState.put("23071", "VA, HARTFIELD");
      zipCityState.put("23072", "VA, HAYES");
      zipCityState.put("23075", "VA, HIGHLAND SPRINGS");
      zipCityState.put("23079", "VA, JAMAICA");
      zipCityState.put("23080", "VA, JAMES STORE");
      zipCityState.put("23083", "VA, JETERSVILLE");
      zipCityState.put("23084", "VA, KENTS STORE");
      zipCityState.put("23085", "VA, KING AND QUEEN C");
      zipCityState.put("23086", "VA, KING WILLIAM");
      zipCityState.put("23089", "VA, LANEXA");
      zipCityState.put("23091", "VA, LITTLE PLYMOUTH");
      zipCityState.put("23092", "VA, LOCUST HILL");
      zipCityState.put("23093", "VA, LOUISA");
      zipCityState.put("23102", "VA, DABNEYS");
      zipCityState.put("23103", "VA, MANAKIN SABOT");
      zipCityState.put("23106", "VA, MANQUIN");
      zipCityState.put("23108", "VA, MASCOT");
      zipCityState.put("23109", "VA, MATHEWS");
      zipCityState.put("23110", "VA, SHANGHAI");
      zipCityState.put("23111", "VA, MECHANICSVILLE");
      zipCityState.put("23112", "VA, MIDLOTHIAN");
      zipCityState.put("23113", "VA, MIDLOTHIAN");
      zipCityState.put("23114", "VA, 23114");
      zipCityState.put("23117", "VA, MINERAL");
      zipCityState.put("23118", "VA, MOBJACK");
      zipCityState.put("23119", "VA, MOON");
      zipCityState.put("23120", "VA, MOSELEY");
      zipCityState.put("23123", "VA, NEW CANTON");
      zipCityState.put("23124", "VA, NEW KENT");
      zipCityState.put("23125", "VA, NEW POINT");
      zipCityState.put("23126", "VA, NEWTOWN");
      zipCityState.put("23128", "VA, NORTH");
      zipCityState.put("23129", "VA, OILVILLE");
      zipCityState.put("23130", "VA, ONEMO");
      zipCityState.put("23137", "VA, 23137");
      zipCityState.put("23138", "VA, BAVON");
      zipCityState.put("23139", "VA, POWHATAN");
      zipCityState.put("23140", "VA, PROVIDENCE FORGE");
      zipCityState.put("23141", "VA, QUINTON");
      zipCityState.put("23146", "VA, ROCKVILLE");
      zipCityState.put("23148", "VA, INDIAN NECK");
      zipCityState.put("23149", "VA, SALUDA");
      zipCityState.put("23150", "VA, SANDSTON");
      zipCityState.put("23153", "VA, SANDY HOOK");
      zipCityState.put("23156", "VA, PLAIN VIEW");
      zipCityState.put("23157", "VA, 23157");
      zipCityState.put("23161", "VA, STEVENSVILLE");
      zipCityState.put("23163", "VA, SHADOW");
      zipCityState.put("23168", "VA, TOANO");
      zipCityState.put("23169", "VA, SYRINGA");
      zipCityState.put("23175", "VA, REMLIK");
      zipCityState.put("23176", "VA, WAKE");
      zipCityState.put("23177", "VA, WALKERTON");
      zipCityState.put("23179", "VA, WARNER");
      zipCityState.put("23180", "VA, WATER VIEW");
      zipCityState.put("23181", "VA, WEST POINT");
      zipCityState.put("23185", "VA, MERRIMAC");
      zipCityState.put("23188", "VA, WILLIAMSBURG");
      zipCityState.put("23192", "VA, MONTPELIER");
      zipCityState.put("23219", "VA, RICHMOND");
      zipCityState.put("23220", "VA, RICHMOND");
      zipCityState.put("23221", "VA, RICHMOND");
      zipCityState.put("23222", "VA, RICHMOND");
      zipCityState.put("23223", "VA, RICHMOND");
      zipCityState.put("23224", "VA, RICHMOND");
      zipCityState.put("23225", "VA, RICHMOND");
      zipCityState.put("23226", "VA, RICHMOND");
      zipCityState.put("23227", "VA, BELLEVUE");
      zipCityState.put("23228", "VA, LAKESIDE");
      zipCityState.put("23229", "VA, REGENCY");
      zipCityState.put("23230", "VA, WEST END");
      zipCityState.put("23231", "VA, RICHMOND");
      zipCityState.put("23233", "VA, RIDGE");
      zipCityState.put("23234", "VA, AMPTHILL");
      zipCityState.put("23235", "VA, BON AIR");
      zipCityState.put("23236", "VA, RICHMOND");
      zipCityState.put("23237", "VA, RICHMOND");
      zipCityState.put("23294", "VA, RICHMOND");
      zipCityState.put("23301", "VA, ACCOMAC");
      zipCityState.put("23302", "VA, ASSAWOMAN");
      zipCityState.put("23306", "VA, BELLE HAVEN");
      zipCityState.put("23307", "VA, BIRDSNEST");
      zipCityState.put("23308", "VA, BLOXOM");
      zipCityState.put("23310", "VA, CAPE CHARLES");
      zipCityState.put("23314", "VA, CARROLLTON");
      zipCityState.put("23315", "VA, CARRSVILLE");
      zipCityState.put("23320", "VA, CHESAPEAKE");
      zipCityState.put("23321", "VA, BOWERS HILL");
      zipCityState.put("23322", "VA, FENTRESS");
      zipCityState.put("23323", "VA, CHESAPEAKE");
      zipCityState.put("23324", "VA, CHESAPEAKE");
      zipCityState.put("23325", "VA, CHESAPEAKE");
      zipCityState.put("23336", "VA, CHINCOTEAGUE");
      zipCityState.put("23337", "VA, WALLOPS ISLAND");
      zipCityState.put("23350", "VA, EXMORE");
      zipCityState.put("23354", "VA, FRANKTOWN");
      zipCityState.put("23356", "VA, GREENBACKVILLE");
      zipCityState.put("23357", "VA, GREENBUSH");
      zipCityState.put("23359", "VA, HALLWOOD");
      zipCityState.put("23395", "VA, HORNTOWN");
      zipCityState.put("23396", "VA, HORSEY");
      zipCityState.put("23399", "VA, JENKINS BRIDGE");
      zipCityState.put("23404", "VA, LOCUSTVILLE");
      zipCityState.put("23405", "VA, MACHIPONGO");
      zipCityState.put("23407", "VA, MAPPSVILLE");
      zipCityState.put("23409", "VA, MEARS");
      zipCityState.put("23410", "VA, MELFA");
      zipCityState.put("23415", "VA, NEW CHURCH");
      zipCityState.put("23416", "VA, OAK HALL");
      zipCityState.put("23417", "VA, ONANCOCK");
      zipCityState.put("23418", "VA, ONLEY");
      zipCityState.put("23420", "VA, PAINTER");
      zipCityState.put("23421", "VA, PARKSLEY");
      zipCityState.put("23426", "VA, SANFORD");
      zipCityState.put("23430", "VA, SMITHFIELD");
      zipCityState.put("23432", "VA, SUFFOLK");
      zipCityState.put("23433", "VA, SUFFOLK");
      zipCityState.put("23434", "VA, SUFFOLK");
      zipCityState.put("23435", "VA, SUFFOLK");
      zipCityState.put("23436", "VA, SUFFOLK");
      zipCityState.put("23437", "VA, SUFFOLK");
      zipCityState.put("23438", "VA, SUFFOLK");
      zipCityState.put("23440", "VA, TANGIER");
      zipCityState.put("23442", "VA, TEMPERANCEVILLE");
      zipCityState.put("23451", "VA, VIRGINIA BEACH");
      zipCityState.put("23452", "VA, VIRGINIA BEACH");
      zipCityState.put("23454", "VA, VIRGINIA BEACH");
      zipCityState.put("23455", "VA, VIRGINIA BEACH");
      zipCityState.put("23456", "VA, VIRGINIA BEACH");
      zipCityState.put("23457", "VA, BLACKWATER BRIDG");
      zipCityState.put("23459", "VA, VIRGINIA BEACH");
      zipCityState.put("23462", "VA, VIRGINIA BEACH");
      zipCityState.put("23464", "VA, VIRGINIA BEACH");
      zipCityState.put("23481", "VA, WALTERS");
      zipCityState.put("23487", "VA, WINDSOR");
      zipCityState.put("23502", "VA, NORFOLK");
      zipCityState.put("23503", "VA, NORFOLK");
      zipCityState.put("23504", "VA, NORFOLK");
      zipCityState.put("23505", "VA, NORFOLK");
      zipCityState.put("23507", "VA, NORFOLK");
      zipCityState.put("23508", "VA, NORFOLK");
      zipCityState.put("23509", "VA, NORFOLK");
      zipCityState.put("23510", "VA, NORFOLK");
      zipCityState.put("23511", "VA, FLEET");
      zipCityState.put("23513", "VA, NORFOLK");
      zipCityState.put("23517", "VA, NORFOLK");
      zipCityState.put("23518", "VA, NORFOLK");
      zipCityState.put("23521", "VA, NAVAL AMPHIBIOUS");
      zipCityState.put("23523", "VA, NORFOLK");
      zipCityState.put("23601", "VA, NEWPORT NEWS");
      zipCityState.put("23602", "VA, NEWPORT NEWS");
      zipCityState.put("23603", "VA, NEWPORT NEWS");
      zipCityState.put("23604", "VA, NEWPORT NEWS");
      zipCityState.put("23605", "VA, NEWPORT NEWS");
      zipCityState.put("23606", "VA, NEWPORT NEWS");
      zipCityState.put("23607", "VA, NEWPORT NEWS");
      zipCityState.put("23651", "VA, HAMPTON");
      zipCityState.put("23661", "VA, HAMPTON");
      zipCityState.put("23662", "VA, POQUOSON");
      zipCityState.put("23663", "VA, HAMPTON");
      zipCityState.put("23664", "VA, HAMPTON");
      zipCityState.put("23665", "VA, HAMPTON");
      zipCityState.put("23666", "VA, HAMPTON");
      zipCityState.put("23669", "VA, HAMPTON");
      zipCityState.put("23690", "VA, YORKTOWN");
      zipCityState.put("23692", "VA, GRAFTON");
      zipCityState.put("23693", "VA, TABB");
      zipCityState.put("23696", "VA, SEAFORD");
      zipCityState.put("23701", "VA, PORTSMOUTH");
      zipCityState.put("23702", "VA, PORTSMOUTH");
      zipCityState.put("23703", "VA, PORTSMOUTH");
      zipCityState.put("23704", "VA, PORTSMOUTH");
      zipCityState.put("23707", "VA, PORTSMOUTH");
      zipCityState.put("23709", "VA, PORTSMOUTH");
      zipCityState.put("23801", "VA, FORT LEE");
      zipCityState.put("23803", "VA, ETTRICK");
      zipCityState.put("23805", "VA, PETERSBURG");
      zipCityState.put("23821", "VA, ALBERTA");
      zipCityState.put("23824", "VA, BLACKSTONE");
      zipCityState.put("23827", "VA, BOYKINS");
      zipCityState.put("23828", "VA, BRANCHVILLE");
      zipCityState.put("23829", "VA, CAPRON");
      zipCityState.put("23830", "VA, CARSON");
      zipCityState.put("23831", "VA, CHESTER");
      zipCityState.put("23832", "VA, CHESTERFIELD");
      zipCityState.put("23833", "VA, CHURCH ROAD");
      zipCityState.put("23834", "VA, COLONIAL HEIGHTS");
      zipCityState.put("23837", "VA, COURTLAND");
      zipCityState.put("23839", "VA, DENDRON");
      zipCityState.put("23840", "VA, DEWITT");
      zipCityState.put("23841", "VA, DINWIDDIE");
      zipCityState.put("23842", "VA, DISPUTANTA");
      zipCityState.put("23843", "VA, DOLPHIN");
      zipCityState.put("23844", "VA, DREWRYVILLE");
      zipCityState.put("23845", "VA, EBONY");
      zipCityState.put("23846", "VA, ELBERON");
      zipCityState.put("23847", "VA, EMPORIA");
      zipCityState.put("23850", "VA, AMMON");
      zipCityState.put("23851", "VA, FRANKLIN");
      zipCityState.put("23856", "VA, FREEMAN");
      zipCityState.put("23857", "VA, GASBURG");
      zipCityState.put("23859", "VA, HANDSOM");
      zipCityState.put("23860", "VA, HOPEWELL");
      zipCityState.put("23866", "VA, IVOR");
      zipCityState.put("23867", "VA, JARRATT");
      zipCityState.put("23868", "VA, TRIPLET");
      zipCityState.put("23872", "VA, MC KENNEY");
      zipCityState.put("23874", "VA, NEWSOMS");
      zipCityState.put("23875", "VA, PRINCE GEORGE");
      zipCityState.put("23876", "VA, RAWLINGS");
      zipCityState.put("23878", "VA, SEDLEY");
      zipCityState.put("23879", "VA, SKIPPERS");
      zipCityState.put("23881", "VA, SPRING GROVE");
      zipCityState.put("23882", "VA, STONY CREEK");
      zipCityState.put("23883", "VA, SURRY");
      zipCityState.put("23885", "VA, SUTHERLAND");
      zipCityState.put("23887", "VA, VALENTINES");
      zipCityState.put("23888", "VA, WAKEFIELD");
      zipCityState.put("23889", "VA, WARFIELD");
      zipCityState.put("23890", "VA, WAVERLY");
      zipCityState.put("23893", "VA, WHITE PLAINS");
      zipCityState.put("23894", "VA, WILSONS");
      zipCityState.put("23897", "VA, YALE");
      zipCityState.put("23898", "VA, ZUNI");
      zipCityState.put("23901", "VA, FARMVILLE");
      zipCityState.put("23915", "VA, BASKERVILLE");
      zipCityState.put("23917", "VA, BOYDTON");
      zipCityState.put("23919", "VA, BRACEY");
      zipCityState.put("23920", "VA, BRODNAX");
      zipCityState.put("23921", "VA, BUCKINGHAM");
      zipCityState.put("23922", "VA, BURKEVILLE");
      zipCityState.put("23923", "VA, CHARLOTTE COURT");
      zipCityState.put("23924", "VA, CHASE CITY");
      zipCityState.put("23927", "VA, CLARKSVILLE");
      zipCityState.put("23930", "VA, CREWE");
      zipCityState.put("23934", "VA, CULLEN");
      zipCityState.put("23936", "VA, SPROUSES CORNER");
      zipCityState.put("23937", "VA, DRAKES BRANCH");
      zipCityState.put("23938", "VA, DUNDAS");
      zipCityState.put("23942", "VA, GREEN BAY");
      zipCityState.put("23944", "VA, KENBRIDGE");
      zipCityState.put("23947", "VA, KEYSVILLE");
      zipCityState.put("23950", "VA, BLACKRIDGE");
      zipCityState.put("23952", "VA, LUNENBURG");
      zipCityState.put("23954", "VA, MEHERRIN");
      zipCityState.put("23958", "VA, PAMPLIN");
      zipCityState.put("23959", "VA, PHENIX");
      zipCityState.put("23960", "VA, PROSPECT");
      zipCityState.put("23962", "VA, RANDOLPH");
      zipCityState.put("23963", "VA, RED HOUSE");
      zipCityState.put("23964", "VA, RED OAK");
      zipCityState.put("23966", "VA, RICE");
      zipCityState.put("23967", "VA, SAXE");
      zipCityState.put("23968", "VA, SKIPWITH");
      zipCityState.put("23970", "VA, SOUTH HILL");
      zipCityState.put("23973", "VA, 23973");
      zipCityState.put("23974", "VA, VICTORIA");
      zipCityState.put("23976", "VA, WYLLIESBURG");
      zipCityState.put("24011", "VA, ROANOKE");
      zipCityState.put("24012", "VA, ROANOKE");
      zipCityState.put("24013", "VA, ROANOKE");
      zipCityState.put("24014", "VA, ROANOKE");
      zipCityState.put("24015", "VA, ROANOKE");
      zipCityState.put("24016", "VA, ROANOKE");
      zipCityState.put("24017", "VA, ROANOKE");
      zipCityState.put("24018", "VA, CAVE SPRING");
      zipCityState.put("24019", "VA, HOLLINS");
      zipCityState.put("24053", "VA, ARARAT");
      zipCityState.put("24054", "VA, AXTON");
      zipCityState.put("24055", "VA, BASSETT");
      zipCityState.put("24059", "VA, BENT MOUNTAIN");
      zipCityState.put("24060", "VA, WHITETHORNE");
      zipCityState.put("24064", "VA, BLUE RIDGE");
      zipCityState.put("24065", "VA, BOONES MILL");
      zipCityState.put("24066", "VA, LITHIA");
      zipCityState.put("24067", "VA, CALLAWAY");
      zipCityState.put("24069", "VA, CASCADE");
      zipCityState.put("24070", "VA, CATAWBA");
      zipCityState.put("24072", "VA, SIMPSONS");
      zipCityState.put("24073", "VA, CHRISTIANSBURG");
      zipCityState.put("24076", "VA, CLAUDVILLE");
      zipCityState.put("24077", "VA, CLOVERDALE");
      zipCityState.put("24078", "VA, COLLINSVILLE");
      zipCityState.put("24079", "VA, COPPER HILL");
      zipCityState.put("24082", "VA, CRITZ");
      zipCityState.put("24083", "VA, DALEVILLE");
      zipCityState.put("24084", "VA, DUBLIN");
      zipCityState.put("24085", "VA, EAGLE ROCK");
      zipCityState.put("24086", "VA, EGGLESTON");
      zipCityState.put("24087", "VA, IRONTO");
      zipCityState.put("24088", "VA, FERRUM");
      zipCityState.put("24089", "VA, FIELDALE");
      zipCityState.put("24090", "VA, FINCASTLE");
      zipCityState.put("24091", "VA, ALUM RIDGE");
      zipCityState.put("24092", "VA, GLADEHILL");
      zipCityState.put("24093", "VA, GLEN LYN");
      zipCityState.put("24094", "VA, GOLDBOND");
      zipCityState.put("24095", "VA, GOODVIEW");
      zipCityState.put("24101", "VA, HARDY");
      zipCityState.put("24102", "VA, HENRY");
      zipCityState.put("24104", "VA, HUDDLESTON");
      zipCityState.put("24105", "VA, INDIAN VALLEY");
      zipCityState.put("24112", "VA, MARTINSVILLE");
      zipCityState.put("24120", "VA, MEADOWS OF DAN");
      zipCityState.put("24121", "VA, MONETA");
      zipCityState.put("24122", "VA, MONTVALE");
      zipCityState.put("24124", "VA, NARROWS");
      zipCityState.put("24127", "VA, NEW CASTLE");
      zipCityState.put("24128", "VA, NEWPORT");
      zipCityState.put("24131", "VA, PAINT BANK");
      zipCityState.put("24133", "VA, PATRICK SPRINGS");
      zipCityState.put("24134", "VA, PEARISBURG");
      zipCityState.put("24136", "VA, MOUNTAIN LAKE");
      zipCityState.put("24137", "VA, PENHOOK");
      zipCityState.put("24138", "VA, PILOT");
      zipCityState.put("24139", "VA, PITTSVILLE");
      zipCityState.put("24141", "VA, FAIRLAWN");
      zipCityState.put("24147", "VA, RICH CREEK");
      zipCityState.put("24148", "VA, RIDGEWAY");
      zipCityState.put("24149", "VA, RINER");
      zipCityState.put("24150", "VA, RIPPLEMEAD");
      zipCityState.put("24151", "VA, ROCKY MOUNT");
      zipCityState.put("24153", "VA, SALEM");
      zipCityState.put("24161", "VA, SANDY LEVEL");
      zipCityState.put("24162", "VA, SHAWSVILLE");
      zipCityState.put("24165", "VA, SPENCER");
      zipCityState.put("24167", "VA, STAFFORDSVILLE");
      zipCityState.put("24168", "VA, STANLEYTOWN");
      zipCityState.put("24171", "VA, STUART");
      zipCityState.put("24174", "VA, THAXTON");
      zipCityState.put("24175", "VA, TROUTVILLE");
      zipCityState.put("24176", "VA, UNION HALL");
      zipCityState.put("24179", "VA, STEWARTSVILLE");
      zipCityState.put("24184", "VA, WIRTZ");
      zipCityState.put("24185", "VA, WOOLWINE");
      zipCityState.put("24201", "VA, BRISTOL");
      zipCityState.put("24210", "VA, ABINGDON");
      zipCityState.put("24216", "VA, EXETER");
      zipCityState.put("24217", "VA, BEE");
      zipCityState.put("24219", "VA, BIG STONE GAP");
      zipCityState.put("24220", "VA, BIRCHLEAF");
      zipCityState.put("24221", "VA, BLACKWATER");
      zipCityState.put("24224", "VA, CASTLEWOOD");
      zipCityState.put("24225", "VA, CLEVELAND");
      zipCityState.put("24226", "VA, CLINCHCO");
      zipCityState.put("24228", "VA, CLINTWOOD");
      zipCityState.put("24230", "VA, COEBURN");
      zipCityState.put("24236", "VA, DAMASCUS");
      zipCityState.put("24237", "VA, DANTE");
      zipCityState.put("24239", "VA, DAVENPORT");
      zipCityState.put("24243", "VA, DRYDEN");
      zipCityState.put("24244", "VA, CLINCHPORT");
      zipCityState.put("24245", "VA, DUNGANNON");
      zipCityState.put("24248", "VA, EWING");
      zipCityState.put("24250", "VA, FORT BLACKMORE");
      zipCityState.put("24251", "VA, GATE CITY");
      zipCityState.put("24256", "VA, HAYSI");
      zipCityState.put("24258", "VA, HILTONS");
      zipCityState.put("24260", "VA, COUNCIL");
      zipCityState.put("24263", "VA, JONESVILLE");
      zipCityState.put("24265", "VA, KEOKEE");
      zipCityState.put("24266", "VA, LEBANON");
      zipCityState.put("24269", "VA, MC CLURE");
      zipCityState.put("24270", "VA, MENDOTA");
      zipCityState.put("24271", "VA, NICKELSVILLE");
      zipCityState.put("24272", "VA, NORA");
      zipCityState.put("24273", "VA, NORTON");
      zipCityState.put("24277", "VA, PENNINGTON GAP");
      zipCityState.put("24279", "VA, POUND");
      zipCityState.put("24280", "VA, ROSEDALE");
      zipCityState.put("24281", "VA, ROSE HILL");
      zipCityState.put("24282", "VA, SAINT CHARLES");
      zipCityState.put("24283", "VA, SAINT PAUL");
      zipCityState.put("24285", "VA, STONEGA");
      zipCityState.put("24289", "VA, TRAMMEL");
      zipCityState.put("24290", "VA, WEBER CITY");
      zipCityState.put("24292", "VA, WHITETOP");
      zipCityState.put("24293", "VA, WISE");
      zipCityState.put("24301", "VA, PULASKI");
      zipCityState.put("24311", "VA, ATKINS");
      zipCityState.put("24312", "VA, AUSTINVILLE");
      zipCityState.put("24313", "VA, BARREN SPRINGS");
      zipCityState.put("24314", "VA, BASTIAN");
      zipCityState.put("24315", "VA, BLAND");
      zipCityState.put("24316", "VA, BROADFORD");
      zipCityState.put("24317", "VA, CANA");
      zipCityState.put("24318", "VA, CERES");
      zipCityState.put("24319", "VA, CHILHOWIE");
      zipCityState.put("24322", "VA, CRIPPLE CREEK");
      zipCityState.put("24323", "VA, CROCKETT");
      zipCityState.put("24324", "VA, DRAPER");
      zipCityState.put("24325", "VA, DUGSPUR");
      zipCityState.put("24326", "VA, ELK CREEK");
      zipCityState.put("24328", "VA, FANCY GAP");
      zipCityState.put("24329", "VA, 24329");
      zipCityState.put("24330", "VA, FRIES");
      zipCityState.put("24333", "VA, GALAX");
      zipCityState.put("24340", "VA, GLADE SPRING");
      zipCityState.put("24343", "VA, HILLSVILLE");
      zipCityState.put("24347", "VA, ALLISONIA");
      zipCityState.put("24348", "VA, INDEPENDENCE");
      zipCityState.put("24350", "VA, IVANHOE");
      zipCityState.put("24351", "VA, LAMBSBURG");
      zipCityState.put("24352", "VA, LAUREL FORK");
      zipCityState.put("24354", "VA, MARION");
      zipCityState.put("24360", "VA, FOSTER FALLS");
      zipCityState.put("24361", "VA, MEADOWVIEW");
      zipCityState.put("24363", "VA, MOUTH OF WILSON");
      zipCityState.put("24366", "VA, ROCKY GAP");
      zipCityState.put("24368", "VA, RURAL RETREAT");
      zipCityState.put("24370", "VA, SALTVILLE");
      zipCityState.put("24373", "VA, SEVEN MILE FORD");
      zipCityState.put("24374", "VA, SPEEDWELL");
      zipCityState.put("24375", "VA, SUGAR GROVE");
      zipCityState.put("24377", "VA, TANNERSVILLE");
      zipCityState.put("24378", "VA, TROUT DALE");
      zipCityState.put("24380", "VA, WILLIS");
      zipCityState.put("24381", "VA, WOODLAWN");
      zipCityState.put("24382", "VA, WYTHEVILLE");
      zipCityState.put("24401", "VA, WOODRUM");
      zipCityState.put("24413", "VA, BLUE GRASS");
      zipCityState.put("24416", "VA, BUENA VISTA");
      zipCityState.put("24421", "VA, CHURCHVILLE");
      zipCityState.put("24422", "VA, CLIFTON FORGE");
      zipCityState.put("24426", "VA, ALLEGHANY");
      zipCityState.put("24430", "VA, CRAIGSVILLE");
      zipCityState.put("24431", "VA, CRIMORA");
      zipCityState.put("24432", "VA, DEERFIELD");
      zipCityState.put("24433", "VA, DOE HILL");
      zipCityState.put("24435", "VA, FAIRFIELD");
      zipCityState.put("24437", "VA, FORT DEFIANCE");
      zipCityState.put("24439", "VA, GOSHEN");
      zipCityState.put("24440", "VA, GREENVILLE");
      zipCityState.put("24441", "VA, GROTTOES");
      zipCityState.put("24442", "VA, HEAD WATERS");
      zipCityState.put("24444", "VA, HIGHTOWN");
      zipCityState.put("24445", "VA, HOT SPRINGS");
      zipCityState.put("24450", "VA, LEXINGTON");
      zipCityState.put("24458", "VA, MC DOWELL");
      zipCityState.put("24459", "VA, MIDDLEBROOK");
      zipCityState.put("24460", "VA, MILLBORO SPRING");
      zipCityState.put("24464", "VA, MONTEBELLO");
      zipCityState.put("24465", "VA, MONTEREY");
      zipCityState.put("24467", "VA, MOUNT SIDNEY");
      zipCityState.put("24468", "VA, MUSTOE");
      zipCityState.put("24471", "VA, PORT REPUBLIC");
      zipCityState.put("24472", "VA, RAPHINE");
      zipCityState.put("24473", "VA, ROCKBRIDGE BATHS");
      zipCityState.put("24475", "VA, SPOTTSWOOD");
      zipCityState.put("24477", "VA, STUARTS DRAFT");
      zipCityState.put("24479", "VA, SWOOPE");
      zipCityState.put("24482", "VA, VERONA");
      zipCityState.put("24483", "VA, VESUVIUS");
      zipCityState.put("24484", "VA, BOLAR");
      zipCityState.put("24485", "VA, WEST AUGUSTA");
      zipCityState.put("24486", "VA, WEYERS CAVE");
      zipCityState.put("24487", "VA, BURNSVILLE");
      zipCityState.put("24501", "VA, LYNCHBURG");
      zipCityState.put("24502", "VA, TIMBERLAKE");
      zipCityState.put("24503", "VA, LYNCHBURG");
      zipCityState.put("24504", "VA, LYNCHBURG");
      zipCityState.put("24517", "VA, ALTAVISTA");
      zipCityState.put("24520", "VA, ALTON");
      zipCityState.put("24521", "VA, AMHERST");
      zipCityState.put("24522", "VA, APPOMATTOX");
      zipCityState.put("24523", "VA, BEDFORD");
      zipCityState.put("24526", "VA, BIG ISLAND");
      zipCityState.put("24527", "VA, BLAIRS");
      zipCityState.put("24528", "VA, BROOKNEAL");
      zipCityState.put("24529", "VA, BUFFALO JUNCTION");
      zipCityState.put("24530", "VA, CALLANDS");
      zipCityState.put("24531", "VA, CHATHAM");
      zipCityState.put("24534", "VA, CLOVER");
      zipCityState.put("24536", "VA, COLEMAN FALLS");
      zipCityState.put("24538", "VA, CONCORD");
      zipCityState.put("24539", "VA, CRYSTAL HILL");
      zipCityState.put("24540", "VA, DANVILLE");
      zipCityState.put("24541", "VA, DANVILLE");
      zipCityState.put("24549", "VA, DRY FORK");
      zipCityState.put("24550", "VA, EVINGTON");
      zipCityState.put("24551", "VA, FOREST");
      zipCityState.put("24553", "VA, GLADSTONE");
      zipCityState.put("24554", "VA, GLADYS");
      zipCityState.put("24555", "VA, GLASGOW");
      zipCityState.put("24556", "VA, GOODE");
      zipCityState.put("24557", "VA, GRETNA");
      zipCityState.put("24558", "VA, HALIFAX");
      zipCityState.put("24562", "VA, HOWARDSVILLE");
      zipCityState.put("24563", "VA, HURT");
      zipCityState.put("24565", "VA, JAVA");
      zipCityState.put("24566", "VA, KEELING");
      zipCityState.put("24569", "VA, LONG ISLAND");
      zipCityState.put("24570", "VA, LOWRY");
      zipCityState.put("24571", "VA, LYNCH STATION");
      zipCityState.put("24572", "VA, MADISON HEIGHTS");
      zipCityState.put("24574", "VA, MONROE");
      zipCityState.put("24577", "VA, LENNIG");
      zipCityState.put("24578", "VA, NATURAL BRIDGE");
      zipCityState.put("24579", "VA, NATURAL BRIDGE S");
      zipCityState.put("24580", "VA, NELSON");
      zipCityState.put("24586", "VA, RINGGOLD");
      zipCityState.put("24588", "VA, RUSTBURG");
      zipCityState.put("24589", "VA, SCOTTSBURG");
      zipCityState.put("24590", "VA, SCOTTSVILLE");
      zipCityState.put("24592", "VA, SOUTH BOSTON");
      zipCityState.put("24593", "VA, SPOUT SPRING");
      zipCityState.put("24594", "VA, SUTHERLIN");
      zipCityState.put("24597", "VA, INGRAM");
      zipCityState.put("24598", "VA, VIRGILINA");
      zipCityState.put("24599", "VA, WINGINA");
      zipCityState.put("24602", "VA, BANDY");
      zipCityState.put("24603", "VA, CONAWAY");
      zipCityState.put("24605", "VA, BLUEFIELD");
      zipCityState.put("24609", "VA, CEDAR BLUFF");
      zipCityState.put("24613", "VA, FALLS MILLS");
      zipCityState.put("24614", "VA, GRUNDY");
      zipCityState.put("24620", "VA, HURLEY");
      zipCityState.put("24622", "VA, JEWELL VALLEY");
      zipCityState.put("24627", "VA, MAVISDALE");
      zipCityState.put("24630", "VA, TIPTOP");
      zipCityState.put("24631", "VA, PATTERSON");
      zipCityState.put("24633", "VA, 24633");
      zipCityState.put("24634", "VA, PILGRIMS KNOB");
      zipCityState.put("24637", "VA, POUNDING MILL");
      zipCityState.put("24639", "VA, RAVEN");
      zipCityState.put("24641", "VA, RICHLANDS");
      zipCityState.put("24646", "VA, ROWE");
      zipCityState.put("24649", "VA, SWORDS CREEK");
      zipCityState.put("24651", "VA, TAZEWELL");
      zipCityState.put("24656", "VA, VANSANT");
      zipCityState.put("24657", "VA, WHITEWOOD");

   }  // end init()
}
